### PR TITLE
Perl::Critic

### PR DESCRIPTION
**Pull request by VadimPushtaev**
Hi.

I believe Strehler is pretty big project to have its own [Perl::Critic](https://metacpan.org/pod/Perl::Critic) system. However, as long as I'm not the author, I don't really know what you consider good or bad.

So I tried to create some scaffold for you. You can merge it as-is, merge and edit, ask me to change what you want or even don't merge it at all and use it as a inspiration for you own Perl::Critic system :).

I also fixed some problems Perl::Critic showed me.

P. S. I got you repo for _Pull request challenge_ this month.

### CODE REVIEW

**Comment by cym0n** [comment]
Hi, great work and thanks for your time spent on Strehler!

I pushed a branch named merge_45, started from yours, if you want to go on collaborating on the issue. What I did on it:

 * Run perlcritic also on test directory t/ and script/strehler. Probably it's useless on test, but I think it's good to have in on the management script, I found a lot of stuff worth of some work. (TODO just for me: strehler script must be deeply tested)
 * Added perlcritic to my Dist::Zilla configuration. Doing that, I turned off TestingAndDebugging::RequireUseStrict because in its opinion Dist::Zilla add module version in the wrong place :-)

Unfortunatly there's still an open issue. Changing eval "require $class" to load $class broke something, test t/006_extra.t returns now a lot of strange errors. I'm trying to find out how to fix it. If I will have to give up, i'll revert that modification excluding the code from critic

**Comment by cym0n** [comment]
All the problems solved!
Branch merged!
Thanks a lot again!

**Comment by VadimPushtaev** [comment]
What about that `load`? What was that problem?

**Comment by cym0n** [comment]
There was a (useless) require in the test script. That plus the Module::Load call made the module been loaded twice, a really bad thing from interpeter point of view!

Here's the commit that fixed: https://github.com/cym0n/strehler/commit/bbdc11a482e07009a53f827f04a0b9e57aaea23c#diff-3856c4a784b9f9ecd515edade68c1b1c

(probably I should get rid of the other require too... but it's working all well right now and I don't want to touch it too much ;-)

**Pull request merged**
